tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "gh"
brew "go"
brew "mas"
brew "neovim"
brew "nodenv"
brew "openjdk"
brew "wget"

cask "docker"
cask "firefox"
cask "jetbrains-toolbox"
cask "visual-studio-code"

mas "Magnet", id: 441258766
