add_newline = true
format = """
[$directory](cyan)\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$gcloud\
$character """

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[package]
disabled = true
